# Generated by Django 5.1.6 on 2025-03-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_clothingitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(default='fallback.png', upload_to=''),
        ),
    ]
