# Generated by Django 5.1.6 on 2025-03-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_alter_clothingitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='price',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='color',
            field=models.TextField(choices=[('white', 'White'), ('black', 'Black'), ('gray', 'Gray'), ('blue', 'Blue'), ('red', 'Red')], default='white'),
        ),
    ]
