# Generated by Django 5.1.6 on 2025-03-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0004_remove_clothingitem_price_clothingitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
